spring.application.name=backend
# 1. Server Configuration
server.port=8081

# 2. Database Connection
spring.datasource.url=jdbc:postgresql://localhost:8080/ShopCart
spring.datasource.username=postgres
spring.datasource.password=Xoqlun@2104
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. JPA/Hibernate Properties
# Cập nhật schema database (update) - Khi chạy lần đầu, hãy dùng "update"
# Sau này ra môi trường thực tế (production) thì chuyển sang "validate" hoặc "none"
spring.jpa.hibernate.ddl-auto=update

# Hiển thị SQL trên console để tiện debug trong quá trình code
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# (Tuỳ chọn) Tránh lỗi liên quan đến session in view
spring.jpa.open-in-view=false

# 4. Logging Configuration